version: '3.4'

services:
  api:
    image: api
    build:
      context: api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
