version: '3.4'

services:
  api:
    image: api
    build:
      context: api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
    volumes:
      - ./api:/usr/src/app
  ui:
    image: ui
    build: 
      context: ui
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./ui:/usr/src/app
